const $=s=>document.querySelector(s),app=$('#app');
const CFG=window.CARBESTIE_CONFIG||{};
const BASE=(CFG.SUPABASE_URL||'https://plhubagdmrlefvnbpqlf.supabase.co').replace(/\/$/,'');
const KEY=CFG.SUPABASE_ANON_KEY||CFG.SUPABASE_PUBLISHABLE_KEY||'';
const APPURL=CFG.APP_URL||'https://carbestie.my';
const STORE={get(k,d){try{return JSON.parse(localStorage.getItem('cb_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('cb_'+k,JSON.stringify(v))},del(k){localStorage.removeItem('cb_'+k)}};
let state={session:STORE.get('session',null),user:null,car:null,services:[],posts:[],tab:'home',loading:true};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM'+Number(n||0).toFixed(2);
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function parseOAuth(){if(!location.hash)return;let p=new URLSearchParams(location.hash.slice(1)),a=p.get('access_token'),r=p.get('refresh_token'),e=p.get('expires_in');if(a){state.session={access_token:a,refresh_token:r,expires_at:Date.now()+Number(e||3600)*1000};STORE.set('session',state.session);history.replaceState({},'',location.pathname+location.search)}}
async function refresh(){if(!state.session?.refresh_token||!KEY)return false;let x=await fetch(BASE+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.session.refresh_token})});if(!x.ok)return false;let j=await x.json();state.session={access_token:j.access_token,refresh_token:j.refresh_token||state.session.refresh_token,expires_at:Date.now()+Number(j.expires_in||3600)*1000};STORE.set('session',state.session);return true}
async function authHeader(){if(state.session?.expires_at&&Date.now()>state.session.expires_at-60000)await refresh();return {apikey:KEY,Authorization:'Bearer '+(state.session?.access_token||''),'Content-Type':'application/json'}}
async function api(path,opt={}){let h=await authHeader(),res=await fetch(BASE+'/rest/v1/'+path,{...opt,headers:{...h,...(opt.headers||{})}});if(!res.ok){let t=await res.text();throw new Error(t||res.statusText)}if(res.status===204)return null;let txt=await res.text();return txt?JSON.parse(txt):null}
async function getUser(){if(!state.session?.access_token||!KEY)return null;let h=await authHeader(),r=await fetch(BASE+'/auth/v1/user',{headers:h});if(!r.ok)return null;return r.json()}
async function loadData(){if(!state.user)return;try{let cars=await api('cars?select=*&order=created_at.asc');state.car=cars?.[0]||null;state.services=state.car?await api('service_records?select=*&car_id=eq.'+encodeURIComponent(state.car.id)+'&order=service_date.desc,created_at.desc'):[];state.posts=await api('community_posts?select=*&order=created_at.desc&limit=50')}catch(e){console.error(e);toast('Could not load data')};state.loading=false}
async function boot(){parseOAuth();if(!KEY){state.loading=false;render();return}state.user=await getUser();if(!state.user&&state.session){STORE.del('session');state.session=null}if(state.user)await loadData();else state.loading=false;render()}
function googleLogin(){if(!KEY)return toast('Supabase publishable key belum dimasukkan');let u=BASE+'/auth/v1/authorize?provider=google&redirect_to='+encodeURIComponent(APPURL);location.href=u}
function logout(){STORE.del('session');state.session=null;state.user=null;state.car=null;state.services=[];state.posts=[];render()}
function login(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="logo">🚗✨</div><h1>Car Bestie</h1><p class="muted">we remember the boring car stuff,<br>so you don't have to.</p><button class="btn" id="google">G&nbsp;&nbsp; Continue with Google</button>${KEY?'':'<div class="notice">Final setup: Supabase publishable key belum dimasukkan.</div>'}</div></div>`;$('#google').onclick=googleLogin}
function nav(){return `<div class="nav">${[['home','🏠','Home'],['service','🔧','Service'],['records','🧾','Records'],['community','💬','Community'],['me','👤','Me']].map(x=>`<button data-tab="${x[0]}" class="${state.tab===x[0]?'active':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div>`}
function shell(content,fab=false){let nm=state.user?.user_metadata?.full_name||state.user?.user_metadata?.name||state.user?.email||'B';app.innerHTML=`<main class="shell"><div class="top"><div class="brand">Car <span>Bestie</span></div><div class="avatar">${esc(String(nm)[0].toUpperCase())}</div></div>${content}</main>${fab?'<button class="fab" id="fab">＋</button>':''}${nav()}`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});if(fab)$('#fab').onclick=serviceModal}
async function upload(bucket,file){let ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=state.user.id+'/'+Date.now()+'.'+ext,h=await authHeader(),r=await fetch(BASE+'/storage/v1/object/'+bucket+'/'+path,{method:'POST',headers:{apikey:KEY,Authorization:h.Authorization,'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});if(!r.ok)throw new Error(await r.text());return path}
async function signed(bucket,path){if(!path)return'';let h=await authHeader(),r=await fetch(BASE+'/storage/v1/object/sign/'+bucket+'/'+path,{method:'POST',headers:h,body:JSON.stringify({expiresIn:3600})});if(!r.ok)return'';let j=await r.json();return BASE+'/storage/v1'+j.signedURL}
function pickFile(cb){let f=$('#filePicker');f.value='';f.onchange=()=>{let file=f.files[0];if(file)cb(file)};f.click()}
async function addCar(){shell(`<div class="hero"><div class="hero-empty" id="photo">📸</div><div class="carname">Add your car</div><p class="muted">A few details and Car Bestie can start remembering for you.</p><div class="form"><button class="btn ghost" id="photoBtn">Take / upload car photo</button><div class="field"><label>Make</label><input id="make" placeholder="Perodua"></div><div class="field"><label>Model</label><input id="model" placeholder="Myvi 1.5"></div><div class="field"><label>Year</label><input id="year" type="number" placeholder="2022"></div><div class="field"><label>Plate number</label><input id="plate" placeholder="VCT 8821"></div><div class="field"><label>Current mileage</label><input id="mileage" type="number" placeholder="54320"></div><div class="field"><label>Nickname (optional)</label><input id="nickname" placeholder="Mimi"></div><button class="btn" id="saveCar">Save my car ♡</button></div></div>`);let photoFile=null;$('#photoBtn').onclick=()=>pickFile(file=>{photoFile=file;let r=new FileReader();r.onload=()=>$('#photo').innerHTML=`<img class="hero-photo" src="${r.result}">`;r.readAsDataURL(file)});$('#saveCar').onclick=async()=>{let make=$('#make').value.trim(),model=$('#model').value.trim();if(!make||!model)return toast('Add make & model first');try{$('#saveCar').disabled=true;let photo_path=photoFile?await upload('car-photos',photoFile):null,payload={user_id:state.user.id,make,model,year:Number($('#year').value)||null,plate_no:$('#plate').value.trim()||null,mileage:Number($('#mileage').value)||0,nickname:$('#nickname').value.trim()||null,photo_path};let rows=await api('cars',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});state.car=rows[0];render()}catch(e){console.error(e);toast('Could not save car')}}}
function recordCard(r){return `<div class="card record"><div class="icon">🔧</div><div><b>${esc(r.service_date||'')}</b><div class="muted">${Number(r.mileage||0).toLocaleString()} km • ${esc(r.workshop||'Workshop')}</div><div class="muted">${esc(r.items||'Service')}</div></div><div class="money">${money(r.total)}</div></div>`}
async function home(){if(!state.car)return addCar();let last=state.services[0],spent=state.services.reduce((a,b)=>a+Number(b.total||0),0),p=await signed('car-photos',state.car.photo_path),photo=p?`<img class="hero-photo" src="${p}">`:`<div class="hero-empty">🚙</div>`;shell(`${photo}<div class="row"><div><div class="carname">${esc(state.car.nickname||state.car.model)}</div><div class="muted">${esc(state.car.make)} ${esc(state.car.model)} • ${esc(state.car.plate_no||'')}</div></div><span class="pill">${Number(state.car.mileage||0).toLocaleString()} km</span></div><div class="section-title">how's your car? ✨</div><div class="grid"><div class="card ok"><b>🛢️ Minyak hitam</b><div class="muted">${last?'recorded ✓':'add first service'}</div></div><div class="card soon"><b>🛞 Tayar</b><div class="muted">check during service 👀</div></div><div class="card"><div class="muted">Total recorded</div><div class="stat">${money(spent)}</div></div><div class="card"><div class="muted">Service records</div><div class="stat">${state.services.length}</div></div></div><div class="section-title">last service</div>${last?recordCard(last):`<div class="card empty"><div class="big">🧾</div>No service record yet.<br><br><button class="btn soft" id="first">I just serviced my car</button></div>`}`,true);if($('#first'))$('#first').onclick=serviceModal}
function service(){shell(`<div class="section-title">Service</div><div class="hero"><h2>just serviced? ✨</h2><p class="muted">Save what was changed, what you paid and your receipt.</p><button class="btn" id="addService">+ Record service</button></div><div class="section-title">reminders</div><div class="card soon"><b>📧 Email reminders</b><p class="muted">Coming next: automatic reminders before service is due.</p></div>`);$('#addService').onclick=serviceModal}
function serviceModal(){if(!state.car)return toast('Add a car first');let w=document.createElement('div');w.className='modal-wrap';w.innerHTML=`<div class="modal"><div class="row"><h2>Record service</h2><button class="btn small ghost" id="close">Close</button></div><div class="form"><div class="field"><label>Date</label><input id="sdate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Mileage</label><input id="smileage" type="number" value="${state.car.mileage||''}"></div><div class="field"><label>Workshop</label><input id="sworkshop" placeholder="ABC Auto Service"></div><div class="field"><label>What was changed?</label><input id="sitems" placeholder="Engine oil, oil filter"></div><div class="field"><label>Total paid (RM)</label><input id="stotal" type="number" step="0.01" placeholder="235"></div><div class="field"><label>Notes</label><textarea id="snotes" placeholder="Optional"></textarea></div><button class="btn ghost" id="receiptBtn">📸 Snap / upload receipt</button><div id="preview"></div><button class="btn" id="saveService">Save service ♡</button></div></div>`;document.body.appendChild(w);let receiptFile=null;w.querySelector('#close').onclick=()=>w.remove();w.querySelector('#receiptBtn').onclick=()=>pickFile(file=>{receiptFile=file;let r=new FileReader();r.onload=()=>w.querySelector('#preview').innerHTML=`<br><img class="receipt" src="${r.result}">`;r.readAsDataURL(file)});w.querySelector('#saveService').onclick=async()=>{try{let receipt_path=receiptFile?await upload('receipts',receiptFile):null,payload={user_id:state.user.id,car_id:state.car.id,service_date:w.querySelector('#sdate').value,mileage:Number(w.querySelector('#smileage').value)||null,workshop:w.querySelector('#sworkshop').value.trim()||null,items:w.querySelector('#sitems').value.trim()||null,total:Number(w.querySelector('#stotal').value)||0,receipt_path,notes:w.querySelector('#snotes').value.trim()||null};let rows=await api('service_records',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});state.services.unshift(rows[0]);if(payload.mileage){state.car.mileage=payload.mileage;await api('cars?id=eq.'+state.car.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({mileage:payload.mileage,updated_at:new Date().toISOString()})})}w.remove();toast('Service saved ✨');render()}catch(e){console.error(e);toast('Could not save service')}}}
async function records(){let html='';for(let r of state.services){let u=await signed('receipts',r.receipt_path);html+=recordCard(r)+(u?`<div class="card"><a href="${u}" target="_blank">📸 View receipt</a></div>`:'')}shell(`<div class="section-title">your car history 🧾</div>${html||`<div class="empty"><div class="big">🧾</div>Your receipts & service history will appear here.</div>`}`)}
function community(){let nm=state.user?.user_metadata?.full_name||state.user?.user_metadata?.name||'Bestie';shell(`<div class="row"><div class="section-title">car talk 💬</div><button class="btn small soft" id="post">+ Post</button></div><p class="muted">Members only. Anonymous to the community, but linked to your account for moderation.</p>${state.posts.map(p=>`<div class="card community-post"><div class="meta">${p.is_anonymous?'Anonymous':esc(p.display_name||'Member')} • ${esc(p.location||'Malaysia')}</div><p>${esc(p.body)}</p><div class="muted">${p.user_id===state.user.id?'Your post':''}</div></div>`).join('')||'<div class="empty">Be the first to start Car Talk ✨</div>'}`);$('#post').onclick=()=>postModal(nm)}
function postModal(nm){let w=document.createElement('div');w.className='modal-wrap';w.innerHTML=`<div class="modal"><h2>New post</h2><div class="form"><div class="field"><label>What's on your mind?</label><textarea id="text" placeholder="Workshop recommendation, price check, car question..."></textarea></div><div class="field"><label>Area</label><input id="place" placeholder="Kuantan"></div><label><input id="anon" type="checkbox" checked> Post anonymously</label><button class="btn" id="publish">Post to Car Talk</button><button class="btn ghost" id="cancel">Cancel</button></div></div>`;document.body.appendChild(w);w.querySelector('#cancel').onclick=()=>w.remove();w.querySelector('#publish').onclick=async()=>{let body=w.querySelector('#text').value.trim();if(!body)return;try{let rows=await api('community_posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:state.user.id,display_name:nm,is_anonymous:w.querySelector('#anon').checked,location:w.querySelector('#place').value.trim()||null,body})});state.posts.unshift(rows[0]);w.remove();render()}catch(e){console.error(e);toast('Could not post')}}}
function me(){let nm=state.user?.user_metadata?.full_name||state.user?.user_metadata?.name||'Bestie';shell(`<div class="section-title">Me</div><div class="card"><b>${esc(nm)}</b><div class="muted">${esc(state.user.email||'')}</div></div><div class="section-title">My car</div>${state.car?`<div class="card"><b>${esc(state.car.make)} ${esc(state.car.model)}</b><div class="muted">${esc(state.car.plate_no||'')}</div></div>`:''}<div class="section-title">Account</div><button class="btn ghost" id="logout">Log out</button>`);$('#logout').onclick=logout}
function render(){if(state.loading)return app.innerHTML='<div class="login"><div class="loginbox"><div class="logo">🚗✨</div><h2>Loading your Car Bestie…</h2></div></div>';if(!state.user)return login();let fn=({home,service,records,community,me}[state.tab]||home);Promise.resolve(fn()).catch(e=>{console.error(e);toast('Something went wrong')})}
boot();