const $=s=>document.querySelector(s),app=$('#app');
const DB={get(k,d){try{return JSON.parse(localStorage.getItem('cb_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('cb_'+k,JSON.stringify(v))}};
let state={user:DB.get('user',null),car:DB.get('car',null),services:DB.get('services',[]),posts:DB.get('posts',[{id:1,anon:true,author:'Anonymous',text:'Ada workshop area Kuantan yang explain elok-elok sebelum tukar parts? First time nak service sendiri 😭',place:'Kuantan',likes:12},{id:2,anon:false,author:'Nadia',text:'Tip: minta quotation dulu sebelum approve. Senang compare dengan rekod dalam app ✨',place:'Shah Alam',likes:18}]),tab:'home'};
const save=()=>{['user','car','services','posts'].forEach(k=>DB.set(k,state[k]))};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM'+Number(n||0).toFixed(2);
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1600)}
function login(){app.innerHTML=`<div class="login"><div class="loginbox"><div class="logo">🚗✨</div><h1>Car Bestie</h1><p class="muted">we remember the boring car stuff,<br>so you don't have to.</p><button class="btn" id="google">G&nbsp;&nbsp; Continue with Google</button><div class="notice">Demo mode: Google OAuth belum disambungkan. Data disimpan pada browser ini sahaja.</div></div></div>`;$('#google').onclick=()=>{state.user={name:'Bestie',email:'demo@carbestie.my'};save();render()}}
function nav(){return `<div class="nav">${[['home','🏠','Home'],['service','🔧','Service'],['records','🧾','Records'],['community','💬','Community'],['me','👤','Me']].map(x=>`<button data-tab="${x[0]}" class="${state.tab===x[0]?'active':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div>`}
function shell(content,fab=false){app.innerHTML=`<main class="shell"><div class="top"><div class="brand">Car <span>Bestie</span></div><div class="avatar">${esc((state.user?.name||'B')[0])}</div></div>${content}</main>${fab?'<button class="fab" id="fab">＋</button>':''}${nav()}`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});if(fab)$('#fab').onclick=serviceModal}
function addCar(){shell(`<div class="hero"><div class="hero-empty" id="photo">📸</div><div class="carname">Add your car</div><p class="muted">A few details and Car Bestie can start remembering for you.</p><div class="form"><button class="btn ghost" id="photoBtn">Take / upload car photo</button><div class="field"><label>Make</label><input id="make" placeholder="Perodua"></div><div class="field"><label>Model</label><input id="model" placeholder="Myvi 1.5"></div><div class="field"><label>Year</label><input id="year" type="number" placeholder="2022"></div><div class="field"><label>Plate number</label><input id="plate" placeholder="VCT 8821"></div><div class="field"><label>Current mileage</label><input id="mileage" type="number" placeholder="54320"></div><div class="field"><label>Nickname (optional)</label><input id="nickname" placeholder="Mimi"></div><button class="btn" id="saveCar">Save my car ♡</button></div></div>`);let photo='';$('#photoBtn').onclick=()=>pickImage(d=>{photo=d;$('#photo').innerHTML=`<img class="hero-photo" src="${d}">`});$('#saveCar').onclick=()=>{if(!$('#make').value.trim()||!$('#model').value.trim())return toast('Add make & model first');state.car={make:$('#make').value.trim(),model:$('#model').value.trim(),year:$('#year').value,plate:$('#plate').value,mileage:$('#mileage').value,nickname:$('#nickname').value,photo};save();render()}}
function recordCard(r){return `<div class="card record"><div class="icon">🔧</div><div><b>${esc(r.date)}</b><div class="muted">${Number(r.mileage||0).toLocaleString()} km • ${esc(r.workshop||'Workshop')}</div><div class="muted">${esc(r.items||'Service')}</div></div><div class="money">${money(r.total)}</div></div>`}
function home(){if(!state.car)return addCar();let last=state.services[0],spent=state.services.reduce((a,b)=>a+Number(b.total||0),0),photo=state.car.photo?`<img class="hero-photo" src="${state.car.photo}">`:`<div class="hero-empty">🚙</div>`;shell(`${photo}<div class="row"><div><div class="carname">${esc(state.car.nickname||state.car.model)}</div><div class="muted">${esc(state.car.make)} ${esc(state.car.model)} • ${esc(state.car.plate)}</div></div><span class="pill">${Number(state.car.mileage||0).toLocaleString()} km</span></div><div class="section-title">how's your car? ✨</div><div class="grid"><div class="card ok"><b>🛢️ Minyak hitam</b><div class="muted">${last?'recorded ✓':'add first service'}</div></div><div class="card soon"><b>🛞 Tayar</b><div class="muted">check during service 👀</div></div><div class="card"><div class="muted">Total recorded</div><div class="stat">${money(spent)}</div></div><div class="card"><div class="muted">Service records</div><div class="stat">${state.services.length}</div></div></div><div class="section-title">last service</div>${last?recordCard(last):`<div class="card empty"><div class="big">🧾</div>No service record yet.<br><br><button class="btn soft" id="first">I just serviced my car</button></div>`}`,true);if($('#first'))$('#first').onclick=serviceModal}
function service(){shell(`<div class="section-title">Service</div><div class="hero"><h2>just serviced? ✨</h2><p class="muted">Save what was changed, what you paid and your receipt.</p><button class="btn" id="addService">+ Record service</button></div><div class="section-title">reminders</div><div class="card soon"><b>📧 Email reminders</b><p class="muted">Akan diaktifkan bila backend Supabase + email provider disambungkan.</p></div>`);$('#addService').onclick=serviceModal}
function serviceModal(){let w=document.createElement('div');w.className='modal-wrap';w.innerHTML=`<div class="modal"><div class="row"><h2>Record service</h2><button class="btn small ghost" id="close">Close</button></div><div class="form"><div class="field"><label>Date</label><input id="sdate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Mileage</label><input id="smileage" type="number" value="${state.car?.mileage||''}"></div><div class="field"><label>Workshop</label><input id="sworkshop" placeholder="ABC Auto Service"></div><div class="field"><label>What was changed?</label><input id="sitems" placeholder="Engine oil, oil filter"></div><div class="field"><label>Total paid (RM)</label><input id="stotal" type="number" step="0.01" placeholder="235"></div><button class="btn ghost" id="receiptBtn">📸 Snap / upload receipt</button><div id="preview"></div><button class="btn" id="saveService">Save service ♡</button></div></div>`;document.body.appendChild(w);let receipt='';w.querySelector('#close').onclick=()=>w.remove();w.querySelector('#receiptBtn').onclick=()=>pickImage(d=>{receipt=d;w.querySelector('#preview').innerHTML=`<br><img class="receipt" src="${d}">`});w.querySelector('#saveService').onclick=()=>{let r={id:Date.now(),date:w.querySelector('#sdate').value,mileage:w.querySelector('#smileage').value,workshop:w.querySelector('#sworkshop').value,items:w.querySelector('#sitems').value,total:w.querySelector('#stotal').value,receipt};state.services.unshift(r);if(state.car)state.car.mileage=r.mileage||state.car.mileage;save();w.remove();toast('Service saved ✨');render()}}
function pickImage(cb){let f=$('#filePicker');f.value='';f.onchange=()=>{let file=f.files[0];if(!file)return;let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)};f.click()}
function records(){shell(`<div class="section-title">your car history 🧾</div>${state.services.length?state.services.map(r=>`${recordCard(r)}${r.receipt?`<img class="receipt" src="${r.receipt}">`:''}`).join(''):`<div class="empty"><div class="big">🧾</div>Your receipts & service history will appear here.</div>`}`)}
function community(){shell(`<div class="row"><div class="section-title">car talk 💬</div><button class="btn small soft" id="post">+ Post</button></div><p class="muted">Members only. Anonymous to the community, but linked to your account for moderation.</p>${state.posts.map(p=>`<div class="card community-post"><div class="meta">${p.anon?'Anonymous':esc(p.author)} • ${esc(p.place||'Malaysia')}</div><p>${esc(p.text)}</p><div class="muted">♡ ${p.likes||0}</div></div>`).join('')}`);$('#post').onclick=postModal}
function postModal(){let w=document.createElement('div');w.className='modal-wrap';w.innerHTML=`<div class="modal"><h2>New post</h2><div class="form"><div class="field"><label>What's on your mind?</label><textarea id="text" placeholder="Workshop recommendation, price check, car question..."></textarea></div><div class="field"><label>Area</label><input id="place" placeholder="Kuantan"></div><label><input id="anon" type="checkbox" checked> Post anonymously</label><button class="btn" id="publish">Post to Car Talk</button><button class="btn ghost" id="cancel">Cancel</button></div></div>`;document.body.appendChild(w);w.querySelector('#cancel').onclick=()=>w.remove();w.querySelector('#publish').onclick=()=>{let t=w.querySelector('#text').value.trim();if(!t)return;state.posts.unshift({id:Date.now(),anon:w.querySelector('#anon').checked,author:state.user.name,text:t,place:w.querySelector('#place').value,likes:0});save();w.remove();render()}}
function me(){shell(`<div class="section-title">Me</div><div class="card"><b>${esc(state.user.name)}</b><div class="muted">${esc(state.user.email)}</div></div><div class="section-title">My car</div>${state.car?`<div class="card"><b>${esc(state.car.make)} ${esc(state.car.model)}</b><div class="muted">${esc(state.car.plate)}</div></div>`:''}<div class="section-title">Account</div><button class="btn ghost" id="logout">Log out</button>`);$('#logout').onclick=()=>{state.user=null;save();render()}}
function render(){if(!state.user)return login();({home,service,records,community,me}[state.tab]||home)()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
